"""rule version category exclusions

Revision ID: 2caf02dcb91f
Revises: f1b7097b452f
Create Date: 2026-08-25 21:26:24.481350

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2caf02dcb91f'
down_revision: Union[str, None] = 'f1b7097b452f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rule_versions', sa.Column('excluded_categories', sa.JSON(), nullable=False))
    op.add_column('rule_versions', sa.Column('gating_only', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rule_versions', 'gating_only')
    op.drop_column('rule_versions', 'excluded_categories')
    # ### end Alembic commands ###
