"""initial schema

Revision ID: f1b7097b452f
Revises: 
Create Date: 2026-08-25 21:13:31.913171

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f1b7097b452f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_categories',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_categories_code'), 'product_categories', ['code'], unique=True)
    op.create_index(op.f('ix_product_categories_id'), 'product_categories', ['id'], unique=False)
    op.create_table('roles',
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('rules',
    sa.Column('rule_key', sa.String(length=64), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rules_id'), 'rules', ['id'], unique=False)
    op.create_index(op.f('ix_rules_rule_key'), 'rules', ['rule_key'], unique=True)
    op.create_table('products',
    sa.Column('canonical_url', sa.Text(), nullable=False),
    sa.Column('url_hash', sa.String(length=64), nullable=False),
    sa.Column('platform', sa.String(length=64), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('brand', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('listed_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('mrp', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('category_confidence', sa.Float(), nullable=True),
    sa.Column('category_manually_overridden', sa.Boolean(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_platform'), 'products', ['platform'], unique=False)
    op.create_index(op.f('ix_products_url_hash'), 'products', ['url_hash'], unique=True)
    op.create_table('rule_versions',
    sa.Column('rule_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('rule_reference', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('requirement', sa.Text(), nullable=False),
    sa.Column('applicability', sa.Text(), nullable=False),
    sa.Column('exceptions', sa.Text(), nullable=True),
    sa.Column('validation_type', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('validator_config', sa.JSON(), nullable=False),
    sa.Column('applicable_categories', sa.JSON(), nullable=False),
    sa.Column('source_document', sa.Text(), nullable=False),
    sa.Column('source_locator', sa.String(length=255), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_until', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_id', 'version_number', name='uq_rule_version')
    )
    op.create_index(op.f('ix_rule_versions_id'), 'rule_versions', ['id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('inspections',
    sa.Column('inspection_number', sa.String(length=32), nullable=False),
    sa.Column('officer_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('platform', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('current_stage', sa.String(length=32), nullable=True),
    sa.Column('overall_status', sa.String(length=32), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['officer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspections_id'), 'inspections', ['id'], unique=False)
    op.create_index(op.f('ix_inspections_inspection_number'), 'inspections', ['inspection_number'], unique=True)
    op.create_index(op.f('ix_inspections_overall_status'), 'inspections', ['overall_status'], unique=False)
    op.create_index(op.f('ix_inspections_status'), 'inspections', ['status'], unique=False)
    op.create_table('compliance_checks',
    sa.Column('inspection_id', sa.Uuid(), nullable=False),
    sa.Column('rule_version_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('checked_fields', sa.JSON(), nullable=False),
    sa.Column('engine_version', sa.String(length=32), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ),
    sa.ForeignKeyConstraint(['rule_version_id'], ['rule_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_checks_id'), 'compliance_checks', ['id'], unique=False)
    op.create_index(op.f('ix_compliance_checks_status'), 'compliance_checks', ['status'], unique=False)
    op.create_table('inspection_sources',
    sa.Column('inspection_id', sa.Uuid(), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspection_sources_id'), 'inspection_sources', ['id'], unique=False)
    op.create_table('pipeline_events',
    sa.Column('inspection_id', sa.Uuid(), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_events_id'), 'pipeline_events', ['id'], unique=False)
    op.create_table('product_images',
    sa.Column('inspection_id', sa.Uuid(), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('original_url', sa.Text(), nullable=True),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('content_type', sa.String(length=64), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('is_blurry', sa.Boolean(), nullable=True),
    sa.Column('blur_score', sa.Float(), nullable=True),
    sa.Column('contrast_score', sa.Float(), nullable=True),
    sa.Column('glare_detected', sa.Boolean(), nullable=True),
    sa.Column('quality_notes', sa.Text(), nullable=True),
    sa.Column('quality_acceptable', sa.Boolean(), nullable=True),
    sa.Column('downloaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_images_id'), 'product_images', ['id'], unique=False)
    op.create_table('reports',
    sa.Column('inspection_id', sa.Uuid(), nullable=False),
    sa.Column('generated_by_id', sa.Uuid(), nullable=False),
    sa.Column('format', sa.String(length=8), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('rule_version_snapshot', sa.JSON(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['generated_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.create_table('web_pages',
    sa.Column('inspection_id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('platform', sa.String(length=64), nullable=True),
    sa.Column('fetch_status', sa.String(length=32), nullable=False),
    sa.Column('http_status_code', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('robots_txt_allowed', sa.Boolean(), nullable=True),
    sa.Column('robots_txt_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scraper_name', sa.String(length=64), nullable=True),
    sa.Column('scraper_version', sa.String(length=32), nullable=True),
    sa.Column('page_hash', sa.String(length=64), nullable=True),
    sa.Column('raw_html_path', sa.Text(), nullable=True),
    sa.Column('raw_metadata', sa.JSON(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_web_pages_id'), 'web_pages', ['id'], unique=False)
    op.create_index(op.f('ix_web_pages_page_hash'), 'web_pages', ['page_hash'], unique=False)
    op.create_table('ocr_results',
    sa.Column('product_image_id', sa.Uuid(), nullable=False),
    sa.Column('engine', sa.String(length=32), nullable=False),
    sa.Column('engine_version', sa.String(length=32), nullable=True),
    sa.Column('model_name', sa.String(length=64), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('bounding_box', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['product_image_id'], ['product_images.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ocr_results_id'), 'ocr_results', ['id'], unique=False)
    op.create_table('review_decisions',
    sa.Column('compliance_check_id', sa.Uuid(), nullable=False),
    sa.Column('reviewer_id', sa.Uuid(), nullable=False),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('automated_status', sa.String(length=32), nullable=False),
    sa.Column('final_status', sa.String(length=32), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('additional_evidence', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['compliance_check_id'], ['compliance_checks.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_decisions_id'), 'review_decisions', ['id'], unique=False)
    op.create_table('violations',
    sa.Column('compliance_check_id', sa.Uuid(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['compliance_check_id'], ['compliance_checks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('compliance_check_id')
    )
    op.create_index(op.f('ix_violations_id'), 'violations', ['id'], unique=False)
    op.create_table('web_extractions',
    sa.Column('web_page_id', sa.Uuid(), nullable=False),
    sa.Column('strategy', sa.String(length=32), nullable=False),
    sa.Column('field_name', sa.String(length=64), nullable=False),
    sa.Column('field_value', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('raw_snippet', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['web_page_id'], ['web_pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_web_extractions_field_name'), 'web_extractions', ['field_name'], unique=False)
    op.create_index(op.f('ix_web_extractions_id'), 'web_extractions', ['id'], unique=False)
    op.create_table('declarations',
    sa.Column('inspection_id', sa.Uuid(), nullable=False),
    sa.Column('field_name', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('normalized_value', sa.Text(), nullable=True),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_web_page_id', sa.Uuid(), nullable=True),
    sa.Column('source_web_extraction_id', sa.Uuid(), nullable=True),
    sa.Column('source_ocr_result_id', sa.Uuid(), nullable=True),
    sa.Column('source_product_image_id', sa.Uuid(), nullable=True),
    sa.Column('source_user_id', sa.Uuid(), nullable=True),
    sa.Column('extraction_method', sa.String(length=64), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ),
    sa.ForeignKeyConstraint(['source_ocr_result_id'], ['ocr_results.id'], ),
    sa.ForeignKeyConstraint(['source_product_image_id'], ['product_images.id'], ),
    sa.ForeignKeyConstraint(['source_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['source_web_extraction_id'], ['web_extractions.id'], ),
    sa.ForeignKeyConstraint(['source_web_page_id'], ['web_pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_declarations_field_name'), 'declarations', ['field_name'], unique=False)
    op.create_index(op.f('ix_declarations_id'), 'declarations', ['id'], unique=False)
    op.create_table('evidence',
    sa.Column('compliance_check_id', sa.Uuid(), nullable=False),
    sa.Column('declaration_id', sa.Uuid(), nullable=True),
    sa.Column('evidence_type', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('reference', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['compliance_check_id'], ['compliance_checks.id'], ),
    sa.ForeignKeyConstraint(['declaration_id'], ['declarations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_id'), 'evidence', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evidence_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_declarations_id'), table_name='declarations')
    op.drop_index(op.f('ix_declarations_field_name'), table_name='declarations')
    op.drop_table('declarations')
    op.drop_index(op.f('ix_web_extractions_id'), table_name='web_extractions')
    op.drop_index(op.f('ix_web_extractions_field_name'), table_name='web_extractions')
    op.drop_table('web_extractions')
    op.drop_index(op.f('ix_violations_id'), table_name='violations')
    op.drop_table('violations')
    op.drop_index(op.f('ix_review_decisions_id'), table_name='review_decisions')
    op.drop_table('review_decisions')
    op.drop_index(op.f('ix_ocr_results_id'), table_name='ocr_results')
    op.drop_table('ocr_results')
    op.drop_index(op.f('ix_web_pages_page_hash'), table_name='web_pages')
    op.drop_index(op.f('ix_web_pages_id'), table_name='web_pages')
    op.drop_table('web_pages')
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_product_images_id'), table_name='product_images')
    op.drop_table('product_images')
    op.drop_index(op.f('ix_pipeline_events_id'), table_name='pipeline_events')
    op.drop_table('pipeline_events')
    op.drop_index(op.f('ix_inspection_sources_id'), table_name='inspection_sources')
    op.drop_table('inspection_sources')
    op.drop_index(op.f('ix_compliance_checks_status'), table_name='compliance_checks')
    op.drop_index(op.f('ix_compliance_checks_id'), table_name='compliance_checks')
    op.drop_table('compliance_checks')
    op.drop_index(op.f('ix_inspections_status'), table_name='inspections')
    op.drop_index(op.f('ix_inspections_overall_status'), table_name='inspections')
    op.drop_index(op.f('ix_inspections_inspection_number'), table_name='inspections')
    op.drop_index(op.f('ix_inspections_id'), table_name='inspections')
    op.drop_table('inspections')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_rule_versions_id'), table_name='rule_versions')
    op.drop_table('rule_versions')
    op.drop_index(op.f('ix_products_url_hash'), table_name='products')
    op.drop_index(op.f('ix_products_platform'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_rules_rule_key'), table_name='rules')
    op.drop_index(op.f('ix_rules_id'), table_name='rules')
    op.drop_table('rules')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_product_categories_id'), table_name='product_categories')
    op.drop_index(op.f('ix_product_categories_code'), table_name='product_categories')
    op.drop_table('product_categories')
    # ### end Alembic commands ###
