"""Builds the data structure the report template renders (Section 17)."""
from __future__ import annotations

import datetime as dt
from dataclasses import dataclass, field

from app.models.inspection import Inspection

DISCLAIMER = (
    "Automated Preliminary Compliance Assessment — Subject to Verification by an "
    "Authorized Officer. This report is generated by LM-SCAN, an AI-assisted "
    "preliminary inspection tool. It is NOT a legally binding determination of "
    "compliance or non-compliance under the Legal Metrology (Packaged Commodities) "
    "Rules, 2011. Every finding must be independently verified by an authorized "
    "Legal Metrology officer before any enforcement action is taken."
)


@dataclass
class ReportContext:
    inspection: Inspection
    generated_by_name: str
    generated_at: dt.datetime
    rule_version_snapshot: list[dict] = field(default_factory=list)
    status_groups: dict[str, list] = field(default_factory=dict)
    disclaimer: str = DISCLAIMER


def build_report_context(inspection: Inspection, generated_by_name: str) -> ReportContext:
    checks = list(inspection.compliance_checks)
    status_groups: dict[str, list] = {
        "PASS": [], "POTENTIAL_NON_COMPLIANCE": [], "NEEDS_MANUAL_REVIEW": [],
        "NOT_APPLICABLE": [], "UNABLE_TO_VERIFY": [],
    }
    rule_version_snapshot = []
    for check in checks:
        status_groups.setdefault(check.status, []).append(check)
        rv = check.rule_version
        rule_version_snapshot.append(
            {
                "rule_key": rv.rule.rule_key,
                "version_number": rv.version_number,
                "rule_reference": rv.rule_reference,
                "source_document": rv.source_document,
                "source_locator": rv.source_locator,
            }
        )

    return ReportContext(
        inspection=inspection,
        generated_by_name=generated_by_name,
        generated_at=dt.datetime.now(dt.timezone.utc),
        rule_version_snapshot=rule_version_snapshot,
        status_groups=status_groups,
    )
