"""Renders and persists inspection reports (Section 17)."""
from __future__ import annotations

import datetime as dt
from pathlib import Path

from jinja2 import Environment, FileSystemLoader, select_autoescape
from sqlalchemy.orm import Session
from xhtml2pdf import pisa

from app.models.inspection import Inspection
from app.models.report import Report
from app.models.user import User
from app.reports.context import (
    STATUS_ORDER,
    break_identifier,
    build_report_context,
    declaration_source_label,
    officer_action,
    short_source_label,
    status_label,
    wrap_long_tokens,
)
from app.storage.files import save_report_bytes

_TEMPLATE_DIR = Path(__file__).resolve().parent / "templates"
_env = Environment(
    loader=FileSystemLoader(str(_TEMPLATE_DIR)),
    autoescape=select_autoescape(["html", "j2"]),
)
# Presentation-only helpers (see app/reports/context.py's module docstring):
# these format existing compliance-check/rule-version data for display —
# they never compute a status, confidence, or evidence value themselves.
_env.globals.update(
    status_label=status_label,
    officer_action=officer_action,
    short_source_label=short_source_label,
    declaration_source_label=declaration_source_label,
    break_identifier=break_identifier,
    wrap_long_tokens=wrap_long_tokens,
    status_order=STATUS_ORDER,
)


def render_report_html(inspection: Inspection, generated_by_name: str) -> str:
    ctx = build_report_context(inspection, generated_by_name)
    template = _env.get_template("inspection_report.html.j2")
    return template.render(ctx=ctx)


def html_to_pdf_bytes(html: str) -> bytes:
    """Pure HTML -> PDF conversion, nothing else. Deliberately does not
    also stamp the header/footer (see `_stamp_header_footer`) so this
    function's signature/behavior stays exactly what existing callers
    (including test_reports.py) already depend on."""
    from io import BytesIO

    buffer = BytesIO()
    result = pisa.CreatePDF(src=html, dest=buffer, encoding="utf-8")
    if result.err:
        raise RuntimeError("PDF generation failed.")
    return buffer.getvalue()


def _stamp_header_footer(pdf_bytes: bytes, *, inspection_number: str, app_version: str, short_disclaimer: str) -> bytes:
    """Overlays a running header (page 2+) and footer (every page, with
    'Page X of Y') onto an already-rendered PDF via a separate
    reportlab + pypdf pass, rather than xhtml2pdf's own `@frame` CSS
    mechanism.

    Why: this installed xhtml2pdf build (0.2.16) has a confirmed
    rendering bug where declaring ANY custom `@frame` region breaks page
    flow -- content from different pages gets superimposed on the same
    page instead of paginating cleanly. This was reproduced with a
    minimal, isolated HTML file containing nothing but a `@frame` and
    plain paragraphs, so it is a renderer limitation, not a symptom of
    this report's own markup. A plain `@page { margin: ... }` (used by
    inspection_report.html.j2) paginates perfectly; this function stamps
    the header/footer into the margin space that CSS reserves, achieving
    the same visual result through a code path that actually works
    reliably (pypdf/reportlab page overlay is a standard, well-supported
    technique, not a brittle one-off hack).

    This never touches report content -- it only draws header/footer
    chrome into the blank margin band `@page` already reserves.
    """
    from io import BytesIO

    from pypdf import PdfReader, PdfWriter
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.units import cm
    from reportlab.pdfgen import canvas

    reader = PdfReader(BytesIO(pdf_bytes))
    page_count = len(reader.pages)

    overlay_buffer = BytesIO()
    c = canvas.Canvas(overlay_buffer, pagesize=A4)
    page_w, page_h = A4
    left_x = 1.5 * cm
    right_x = page_w - 1.5 * cm

    for i in range(page_count):
        if i > 0:
            # Running header, pages 2+ only (page 1 has its own large
            # title block instead — see Section 14 of the redesign brief).
            header_y = page_h - 1.3 * cm
            c.setFont("Helvetica-Bold", 8)
            c.setFillColorRGB(0.2, 0.2, 0.2)
            c.drawString(left_x, header_y, "LM-SCAN  ·  Inspection Report")
            c.setFont("Helvetica", 8)
            c.setFillColorRGB(0.33, 0.33, 0.33)
            c.drawRightString(right_x, header_y, f"Inspection ID: {inspection_number}")
            c.setStrokeColorRGB(0.73, 0.73, 0.73)
            c.setLineWidth(0.4)
            c.line(left_x, header_y - 0.12 * cm, right_x, header_y - 0.12 * cm)

        footer_line_y = 1.9 * cm
        c.setStrokeColorRGB(0.73, 0.73, 0.73)
        c.setLineWidth(0.4)
        c.line(left_x, footer_line_y, right_x, footer_line_y)

        footer_y1 = footer_line_y - 0.35 * cm
        c.setFont("Helvetica", 7)
        c.setFillColorRGB(0.35, 0.35, 0.35)
        c.drawString(left_x, footer_y1, f"Generated by LM-SCAN v{app_version}")
        c.drawRightString(right_x, footer_y1, f"Page {i + 1} of {page_count}")

        footer_y2 = footer_y1 - 0.32 * cm
        c.setFont("Helvetica-Oblique", 6.5)
        c.setFillColorRGB(0.45, 0.45, 0.45)
        c.drawCentredString(page_w / 2, footer_y2, short_disclaimer)

        c.showPage()
    c.save()
    overlay_buffer.seek(0)
    overlay_reader = PdfReader(overlay_buffer)

    writer = PdfWriter()
    for i, page in enumerate(reader.pages):
        page.merge_page(overlay_reader.pages[i])
        writer.add_page(page)

    out = BytesIO()
    writer.write(out)
    return out.getvalue()


def generate_report(db: Session, inspection: Inspection, generated_by: User, fmt: str = "PDF") -> Report:
    html = render_report_html(inspection, generated_by.full_name)
    ctx = build_report_context(inspection, generated_by.full_name)

    if fmt == "PDF":
        content = html_to_pdf_bytes(html)
        content = _stamp_header_footer(
            content,
            inspection_number=inspection.inspection_number,
            app_version=ctx.app_version,
            short_disclaimer=ctx.short_disclaimer,
        )
        extension = "pdf"
    else:
        content = html.encode("utf-8")
        extension = "html"

    file_path = save_report_bytes(inspection.id, content, extension=extension)

    report = Report(
        inspection_id=inspection.id,
        generated_by_id=generated_by.id,
        format=fmt,
        file_path=file_path,
        rule_version_snapshot={"rules": ctx.rule_version_snapshot},
        generated_at=dt.datetime.now(dt.timezone.utc),
    )
    db.add(report)
    db.commit()
    db.refresh(report)
    return report
